apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-app.name" . }}
spec:
  selector:
    app: {{ include "portfolio-app.name" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
